demo/demo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'demo.views.home', name='home'),
    url(r'^', include('proyecto.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

demo/proyecto/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('proyecto.views',
  url(r'^$', 'view_index',name='vista_index'),
  url(r'^proyectos/$', 'view_lista_proyecto',name='vista_lista_proyectos'),
)

demo/proyecto/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
class campo(models.Model):
	lista_campos = (
	('CharField','CHAR'),
	('IntegerField','INT'),
	('BooleanField','BOOLEAN'),
	('BigIntegerField','BIG_INTEGER'),
	('BooleanField','BOOLEAN'),
	
	)
	"""Lista de campos"""
	nombre = models.CharField(blank=True, max_length=100)
	tipo = models.CharField(blank=True, max_length=100,choices=lista_campos)
	longitud = models.FloatField(default=100)
	null = models.BooleanField(default=True)

	
	def __unicode__(self):
		return self.nombre

class tabla(models.Model):
	"""Lista de tablas de una aplicacion"""
	nombre = models.CharField(blank=True, max_length=100)
	campo = models.ManyToManyField(campo)
	def __unicode__(self):
		return self.nombre

class proyecto(models.Model):
	"""Lista de proyectos"""
	user = models.ForeignKey(User)
	nombre = models.CharField(blank=True, max_length=100)
	fecha_creacion = models.DateTimeField(blank=True, default=datetime.datetime.now)
	def __unicode__(self):
		return self.nombre


class configuracion(models.Model):
	"""Lista de configuracion"""
	proyecto = models.ForeignKey(proyecto,unique=True)
	tabla = models.ManyToManyField(tabla)
	tiene_static = models.BooleanField(default=True)
	tiene_media = models.BooleanField(default=True)
	url_static = models.CharField(default="static",blank=True, max_length=100)
	url_media = models.CharField(default="media",blank=True, max_length=100)
	def __unicode__(self):
		return self.proyecto.nombre

demo/proyecto/forms.py
from django import forms
from .models import proyecto
from django.contrib.auth.models import User

class formProyecto(forms.ModelForm):
	#user = forms.ModelMultipleChoiceField(queryset=User.objects.all(),widget=forms.TextInput(attrs={'type': 'hiden'}))
	nombre = forms.CharField(label="Nombre:",widget=forms.TextInput(attrs={'class': 'form-control','aria-describedby':'helpBlock'}))
	class Meta:
		model = proyecto
		fields = {'nombre',}

demo/proyecto/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from .models import proyecto
from .forms import formProyecto
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from datetime import datetime
import simplejson

mes = {
'1':'Enero',
'2':'Febrero',
'3':'Marzo',
'4':'Abril',
'5':'Mayo',
'6':'Junio',
'7':'Julio',
'8':'Agosto',
'9':'Septimbre',
'10':'Octubre',
'11':'Noviembre',
'12':'diciembre',
}





def view_index(request):
	return render_to_response('index.html',
		context_instance=RequestContext(request))




def view_lista_proyecto(request):
	if request.method == "POST":
		if request.is_ajax():
			if "product_id" in request.POST:
				print request.POST
				try:
					id_producto = request.POST['product_id']
					p = proyecto.objects.get(pk=id_producto)
					mensaje = {"status":"True","product_id":p.id}
					p.delete() # Elinamos objeto de la base de datos
					return HttpResponse(simplejson.dumps(mensaje),content_type='application/json')
				except:
					mensaje = {"status":"False"}
					return HttpResponse(simplejson.dumps(mensaje),content_type='application/json')
			if "nombre" in request.POST:
				form = formProyecto(request.POST)
				if form.is_valid():
					p = form.save(commit = False)
					p.user = User.objects.get(pk=request.user.id)
					p.fecha_creacion = fecha = datetime.now()
					p.save()
					msg = {'status':'true',
							'nombre':p.nombre,
							'id':p.id,
							'fecha':fecha.strftime("%d de  %B del %Y alas %H:%M"),
					
							}
					return HttpResponse(simplejson.dumps(msg),content_type='application/json')
				
				else:
					msg  = {'status':'false'}
					return HttpResponse(simplejson.dumps(msg),content_type='application/json')
		else:
			return HttpResponse("Error no se puede mostrar la pagina")
	else:
		lista_proyectos = proyecto.objects.all()
		form = formProyecto()
		ctx = {'form':form,
			  'lista_proyectos':lista_proyectos
		}
		return render_to_response('proyecto/lista.html',ctx,
			context_instance=RequestContext(request))

demo/proyecto/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <link rel="icon" href="{{STATIC_URL}}bootstrap/fonts/apple-touch-icon-precomposed.png">
    <link rel="icon" href="{{STATIC_URL}}bootstrap/fonts/favicon.ico">
    <title>{% block titulo %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{STATIC_URL}}bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{STATIC_URL}}bootstrap/css/navbar-fixed-top.css" rel="stylesheet">

   
  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Mi Projecto</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="{% url  'vista_lista_proyectos' %}">Proyectos</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Default</a></li>
            <li><a href="#">Static top</a></li>
            <li class="active"><a href="#">Fixed top</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
{% block contenido %}
	
{% endblock %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{STATIC_URL}}bootstrap/js/jquery.min.js"></script>
    <script src="{{STATIC_URL}}js/jquery.form.min.js"></script>
    <script src="{{STATIC_URL}}bootstrap/js/bootstrap.min.js"></script>
    
{% block js %}
	
{% endblock %}
    
  </body>
</html>

demo/proyecto/templates/index.html
{% extends "base.html" %}


{% block titulo %}Index{% endblock %}

{% block contenido %}
    <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Navbar example</h1>
        <p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
        <p>To see the difference between static and fixed top navbars, just scroll.</p>
        <p>
          <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
        </p>
      </div>

    </div> <!-- /container -->

{% endblock %}

demo/proyecto/templates/proyecto/lista.html
{% extends "base.html" %}

{% block titulo %}Lista de archivos{% endblock %}


{% block contenido %}

{% include "proyecto/modal/create.html" %}
{% include "proyecto/modal/delete.html" %}

 <div class="container">
		 <div class="jumbotron">
				 <button type="button" class="btn btn-success" data-toggle="modal" data-target="#ModalCreate">Nuevo proyecto</button>
	

    <br>
	<br>

	<div class="panel panel-default">
		<div class="panel-heading">
    		<h3 class="panel-title">Lista de proyectos</h3>
  		</div>
  		<div class="panel-body">
    <table class="table table-striped" id="tabla_proyectos">
      <thead>
        <tr>
          <th>#</th>
          <th>Nombre Proyecto</th>
          <th>Fecha de creacion</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody id="lista_proyectos">
       	{% if lista_proyectos %}
			{% for proyecto in lista_proyectos %}
				
		 <tr id="tr{{proyecto.id}}">
				 <td scope="row">{{proyecto.id}}</td>
          	<td>{{proyecto.nombre}}</td>
         	 <td>{{proyecto.fecha_creacion}}</td>
			 <td>
			 	<button type="button" class="btn btn-info">Configurar</button>
			 	<button id="{{proyecto.id}}" data-name="{{proyecto.nombre}}" type="button" class="btn btn-danger delete" data-toggle="modal" data-target="#ModalDelete">Eliminar</button>
			 </td>
  		</tr>

			{% endfor %}
		{% else %}
			<h4>Aun no has creado ningun proyecto</h4>
		{% endif %}
		
	      </tbody>
    </table>
  
  			</div>
		</div>
	</div> <!-- /jumbotron -->
</div> <!-- /container -->

{% endblock %}


{% block js %}
	<script src="{{STATIC_URL}}js/proyectos.js"></script>
{% endblock %}

demo/proyecto/templates/proyecto/modal/create.html
    <!-- Button to trigger modal -->

<!-- Modal -->
<div class="modal fade" id="ModalCreate" tabindex="-1" role="dialog" aria-labelledby="ModalCreateLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="ModalCreateLabel"></h4>
      </div>
      <div class="modal-body">
        <h1>Escribe el nombre del proyecto</h1>
      </div>
      <div class="modal-footer">
	<form action="" method="POST" id="frProyecto">
			{%csrf_token%}
			<label class="sr-only" for="id_nombre">Input with help text</label>
			{{form.nombre}}
			<span id="helpBlock" class="help-block">Por fabor sin espacios.</span>
        <button id="nueva_carpeta" type="submit" class="btn btn-primary">Guardar</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
    </form>
        

      </div>
    </div>
  </div>
</div>

demo/proyecto/templates/proyecto/modal/delete.html
<div class="modal fade" id="ModalDelete" tabindex="-1" role="dialog" aria-labelledby="ModaldeleteLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="ModalDeleteLabel">Eliminar Proyecto</h4>
      </div>
      <div class="modal-body">
        <p>¿Realmente desea eliminar el proyecto <span id="modal_name"></span>?</p>
      </div>
      <div class="modal-footer">
	<form method="post" id="frmEliminar">
			{%csrf_token%}
	    <input type="hidden" id="modal_idProducto" name="product_id">
        <button id="nueva_carpeta" type="submit" class="btn btn-danger">Eliminar</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>
    </form>
      </div>
    </div>
  </div>
</div>